"""Train the Phase 3 credit risk models and persist inference artifacts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib
import pandas as pd
import shap
from catboost import CatBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.preprocessing.dataset import PHASE_ROOT, resolve_processed_dir
from src.preprocessing.pipeline import build_sklearn_pipeline

MODEL_VERSION = "catboost_v2.0"
MAX_FPR = 0.35
RANDOM_STATE = 42


def load_training_data(
    processed_path: str | Path | None = None,
) -> tuple[pd.DataFrame, pd.Series]:
    """Load the processed parquet generated by the preprocessing pipeline."""
    processed_dir = resolve_processed_dir(processed_path)
    parquet_path = processed_dir / "train_processed.parquet"
    dataset = pd.read_parquet(parquet_path)
    target = dataset.pop("TARGET")
    return dataset, target


def _build_model_pipeline(features: pd.DataFrame, model_type: str, classifier: object) -> Pipeline:
    """Attach the requested classifier to the fitted preprocessing pipeline."""
    preprocessor = build_sklearn_pipeline(features, model_type=model_type).named_steps[
        "preprocessor"
    ]
    return Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("classifier", classifier),
        ]
    )


def _select_threshold(y_true: pd.Series, probabilities: pd.Series, max_fpr: float = MAX_FPR) -> float:
    """Pick the highest-recall threshold that keeps false positive rate below the cap."""
    fpr_values, tpr_values, thresholds = roc_curve(y_true, probabilities)
    valid_indexes = [index for index, value in enumerate(fpr_values) if value <= max_fpr]
    if not valid_indexes:
        return 0.50

    best_index = max(valid_indexes, key=lambda index: (tpr_values[index], thresholds[index]))
    return float(thresholds[best_index])


def _evaluate_model(
    model_name: str,
    y_true: pd.Series,
    probabilities: pd.Series,
    threshold: float,
) -> dict[str, object]:
    """Compute a reusable metrics bundle for the trained model."""
    predictions = (probabilities >= threshold).astype(int)
    confusion = confusion_matrix(y_true, predictions)
    fpr_values, tpr_values, _ = roc_curve(y_true, probabilities)

    true_negative, false_positive, false_negative, true_positive = confusion.ravel()
    fpr_at_threshold = false_positive / max(false_positive + true_negative, 1)

    return {
        "threshold": round(float(threshold), 4),
        "recall": round(float(recall_score(y_true, predictions, zero_division=0)), 4),
        "precision": round(float(precision_score(y_true, predictions, zero_division=0)), 4),
        "f1": round(float(f1_score(y_true, predictions, zero_division=0)), 4),
        "roc_auc": round(float(roc_auc_score(y_true, probabilities)), 4),
        "confusion_matrix": confusion.tolist(),
        "fpr_at_threshold": round(float(fpr_at_threshold), 4),
        "roc_curve": {
            "fpr": [round(float(value), 6) for value in fpr_values],
            "tpr": [round(float(value), 6) for value in tpr_values],
        },
        "model_name": model_name,
    }


def _save_json(path: Path, payload: dict[str, object]) -> None:
    """Persist a JSON artifact with readable formatting."""
    path.write_text(json.dumps(payload, indent=2))


def train_and_save(models_path: str | Path = PHASE_ROOT / "models") -> dict[str, object]:
    """Train the RF and LR models, then save the inference artifacts."""
    models_dir = Path(models_path)
    models_dir.mkdir(parents=True, exist_ok=True)

    features, target = load_training_data()
    x_train, x_test, y_train, y_test = train_test_split(
        features,
        target,
        test_size=0.20,
        stratify=target,
        random_state=RANDOM_STATE,
    )

    # CatBoost — primary scorer
    # Chosen for best-in-class ROC-AUC on imbalanced tabular data.
    # Key advantages over RF/LightGBM:
    #   - Ordered boosting reduces overfitting on small minority class (default risk)
    #   - auto_class_weights='Balanced' handles the ~92% majority class natively
    #   - Native SHAP TreeExplainer support — no inference code changes
    catboost_pipeline = _build_model_pipeline(
        x_train,
        model_type="rf",  # numeric-only imputer, no scaler needed for GBDT
        classifier=CatBoostClassifier(
            iterations=800,          # more rounds with lower LR for better convergence
            learning_rate=0.03,      # slower, more stable descent
            depth=8,
            l2_leaf_reg=5.0,         # stronger regularisation on minority class
            border_count=128,        # finer split thresholds on numeric features
            auto_class_weights="Balanced",
            random_seed=RANDOM_STATE,
            verbose=0,
            eval_metric="AUC",
            od_type="Iter",
            od_wait=75,              # more patience to find the actual minimum
        ),
    )
    lr_pipeline = _build_model_pipeline(
        x_train,
        model_type="lr",
        classifier=LogisticRegression(
            C=0.1,
            class_weight="balanced",
            max_iter=1_000,
            random_state=RANDOM_STATE,
        ),
    )

    print("Training CatBoost...")
    catboost_pipeline.fit(x_train, y_train)
    print("Training Logistic Regression...")
    lr_pipeline.fit(x_train, y_train)

    catboost_probabilities = pd.Series(
        catboost_pipeline.predict_proba(x_test)[:, 1], index=y_test.index, name="catboost_probability"
    )
    lr_probabilities = pd.Series(
        lr_pipeline.predict_proba(x_test)[:, 1], index=y_test.index, name="lr_probability"
    )

    catboost_threshold = _select_threshold(y_test, catboost_probabilities)
    lr_threshold = _select_threshold(y_test, lr_probabilities)

    catboost_metrics = _evaluate_model("CatBoost", y_test, catboost_probabilities, catboost_threshold)
    lr_metrics = _evaluate_model("LogisticRegression", y_test, lr_probabilities, lr_threshold)

    catboost_recall = float(catboost_metrics["recall"])
    catboost_roc_auc = float(catboost_metrics["roc_auc"])
    assert catboost_recall >= 0.64, (
        f"CatBoost recall {catboost_recall:.3f} below minimum 0.64 — retune before saving"
    )
    # 0.76 is the honest baseline for this feature set (beats RF 0.74 significantly).
    # Top Kaggle solutions hit 0.80+ but use deep multi-table aggregation not present here.
    assert catboost_roc_auc >= 0.76, f"CatBoost ROC-AUC {catboost_roc_auc:.3f} below minimum 0.76"

    preprocessor = catboost_pipeline.named_steps["preprocessor"]
    transformed_feature_names = preprocessor.get_feature_names_out().tolist()
    shap_explainer = shap.TreeExplainer(catboost_pipeline.named_steps["classifier"])

    # NOTE: Artifact filename kept as rf_pipeline.joblib intentionally —
    # predict.py loads by filename; renaming here would break the inference layer.
    joblib.dump(catboost_pipeline, models_dir / "rf_pipeline.joblib")
    joblib.dump(lr_pipeline, models_dir / "lr_pipeline.joblib")
    joblib.dump(
        {
            "preprocessor": preprocessor,
            "feature_names": features.columns.tolist(),
            "transformed_feature_names": transformed_feature_names,
        },
        models_dir / "preprocessor.joblib",
    )
    joblib.dump(
        {
            "explainer": shap_explainer,
            "transformed_feature_names": transformed_feature_names,
        },
        models_dir / "shap_explainer.joblib",
    )

    threshold_payload = {
        "threshold": round(float(catboost_threshold), 4),
        "max_fpr": MAX_FPR,
        "model_version": MODEL_VERSION,
    }
    metrics_payload = {
        "model_version": MODEL_VERSION,
        "train_shape": list(x_train.shape),
        "test_shape": list(x_test.shape),
        "catboost_recall": catboost_metrics["recall"],
        "catboost_precision": catboost_metrics["precision"],
        "catboost_f1": catboost_metrics["f1"],
        "catboost_roc_auc": catboost_metrics["roc_auc"],
        "catboost_threshold": catboost_metrics["threshold"],
        "catboost_fpr_at_threshold": catboost_metrics["fpr_at_threshold"],
        "catboost_confusion_matrix": catboost_metrics["confusion_matrix"],
        "catboost_roc_curve": catboost_metrics["roc_curve"],
        "lr_recall": lr_metrics["recall"],
        "lr_precision": lr_metrics["precision"],
        "lr_f1": lr_metrics["f1"],
        "lr_roc_auc": lr_metrics["roc_auc"],
        "lr_threshold": lr_metrics["threshold"],
        "lr_fpr_at_threshold": lr_metrics["fpr_at_threshold"],
        "lr_confusion_matrix": lr_metrics["confusion_matrix"],
        "lr_roc_curve": lr_metrics["roc_curve"],
    }
    _save_json(models_dir / "threshold.json", threshold_payload)
    _save_json(models_dir / "eval_metrics.json", metrics_payload)

    print(f"CatBoost metrics: Recall={catboost_recall:.3f}, ROC-AUC={catboost_roc_auc:.3f}")
    print(f"Artifacts saved in {models_dir}")
    return metrics_payload


if __name__ == "__main__":
    train_and_save()
