"""Train the Phase 2 credit risk models and persist inference artifacts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib
import pandas as pd
import shap
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.preprocessing.dataset import PHASE_ROOT, resolve_processed_dir
from src.preprocessing.pipeline import build_sklearn_pipeline

MODEL_VERSION = "rf_v2.0"
MAX_FPR = 0.35
RANDOM_STATE = 42


def load_training_data(
    processed_path: str | Path | None = None,
) -> tuple[pd.DataFrame, pd.Series]:
    """Load the processed parquet generated by the preprocessing pipeline."""
    processed_dir = resolve_processed_dir(processed_path)
    parquet_path = processed_dir / "train_processed.parquet"
    dataset = pd.read_parquet(parquet_path)
    target = dataset.pop("TARGET")
    return dataset, target


def _build_model_pipeline(features: pd.DataFrame, model_type: str, classifier: object) -> Pipeline:
    """Attach the requested classifier to the fitted preprocessing pipeline."""
    preprocessor = build_sklearn_pipeline(features, model_type=model_type).named_steps[
        "preprocessor"
    ]
    return Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("classifier", classifier),
        ]
    )


def _select_threshold(y_true: pd.Series, probabilities: pd.Series, max_fpr: float = MAX_FPR) -> float:
    """Pick the highest-recall threshold that keeps false positive rate below the cap."""
    fpr_values, tpr_values, thresholds = roc_curve(y_true, probabilities)
    valid_indexes = [index for index, value in enumerate(fpr_values) if value <= max_fpr]
    if not valid_indexes:
        return 0.50

    best_index = max(valid_indexes, key=lambda index: (tpr_values[index], thresholds[index]))
    return float(thresholds[best_index])


def _evaluate_model(
    model_name: str,
    y_true: pd.Series,
    probabilities: pd.Series,
    threshold: float,
) -> dict[str, object]:
    """Compute a reusable metrics bundle for the trained model."""
    predictions = (probabilities >= threshold).astype(int)
    confusion = confusion_matrix(y_true, predictions)
    fpr_values, tpr_values, _ = roc_curve(y_true, probabilities)

    true_negative, false_positive, false_negative, true_positive = confusion.ravel()
    fpr_at_threshold = false_positive / max(false_positive + true_negative, 1)

    return {
        "threshold": round(float(threshold), 4),
        "recall": round(float(recall_score(y_true, predictions, zero_division=0)), 4),
        "precision": round(float(precision_score(y_true, predictions, zero_division=0)), 4),
        "f1": round(float(f1_score(y_true, predictions, zero_division=0)), 4),
        "roc_auc": round(float(roc_auc_score(y_true, probabilities)), 4),
        "confusion_matrix": confusion.tolist(),
        "fpr_at_threshold": round(float(fpr_at_threshold), 4),
        "roc_curve": {
            "fpr": [round(float(value), 6) for value in fpr_values],
            "tpr": [round(float(value), 6) for value in tpr_values],
        },
        "model_name": model_name,
    }


def _save_json(path: Path, payload: dict[str, object]) -> None:
    """Persist a JSON artifact with readable formatting."""
    path.write_text(json.dumps(payload, indent=2))


def train_and_save(models_path: str | Path = PHASE_ROOT / "models") -> dict[str, object]:
    """Train the RF and LR models, then save the inference artifacts."""
    models_dir = Path(models_path)
    models_dir.mkdir(parents=True, exist_ok=True)

    features, target = load_training_data()
    x_train, x_test, y_train, y_test = train_test_split(
        features,
        target,
        test_size=0.20,
        stratify=target,
        random_state=RANDOM_STATE,
    )

    rf_pipeline = _build_model_pipeline(
        x_train,
        model_type="rf",
        classifier=RandomForestClassifier(
            n_estimators=300,
            max_depth=15,
            class_weight="balanced",
            random_state=RANDOM_STATE,
            n_jobs=-1,
        ),
    )
    lr_pipeline = _build_model_pipeline(
        x_train,
        model_type="lr",
        classifier=LogisticRegression(
            C=0.1,
            class_weight="balanced",
            max_iter=1_000,
            random_state=RANDOM_STATE,
        ),
    )

    print("Training Random Forest...")
    rf_pipeline.fit(x_train, y_train)
    print("Training Logistic Regression...")
    lr_pipeline.fit(x_train, y_train)

    rf_probabilities = pd.Series(
        rf_pipeline.predict_proba(x_test)[:, 1], index=y_test.index, name="rf_probability"
    )
    lr_probabilities = pd.Series(
        lr_pipeline.predict_proba(x_test)[:, 1], index=y_test.index, name="lr_probability"
    )

    rf_threshold = _select_threshold(y_test, rf_probabilities)
    lr_threshold = _select_threshold(y_test, lr_probabilities)

    rf_metrics = _evaluate_model("RandomForest", y_test, rf_probabilities, rf_threshold)
    lr_metrics = _evaluate_model("LogisticRegression", y_test, lr_probabilities, lr_threshold)

    rf_recall = float(rf_metrics["recall"])
    rf_roc_auc = float(rf_metrics["roc_auc"])
    assert rf_recall >= 0.64, (
        f"RF recall {rf_recall:.3f} below minimum 0.64 — retune before saving"
    )
    assert rf_roc_auc >= 0.72, f"RF ROC-AUC {rf_roc_auc:.3f} below minimum 0.72"

    preprocessor = rf_pipeline.named_steps["preprocessor"]
    transformed_feature_names = preprocessor.get_feature_names_out().tolist()
    shap_explainer = shap.TreeExplainer(rf_pipeline.named_steps["classifier"])

    joblib.dump(rf_pipeline, models_dir / "rf_pipeline.joblib")
    joblib.dump(lr_pipeline, models_dir / "lr_pipeline.joblib")
    joblib.dump(
        {
            "preprocessor": preprocessor,
            "feature_names": features.columns.tolist(),
            "transformed_feature_names": transformed_feature_names,
        },
        models_dir / "preprocessor.joblib",
    )
    joblib.dump(
        {
            "explainer": shap_explainer,
            "transformed_feature_names": transformed_feature_names,
        },
        models_dir / "shap_explainer.joblib",
    )

    threshold_payload = {
        "threshold": round(float(rf_threshold), 4),
        "max_fpr": MAX_FPR,
        "model_version": MODEL_VERSION,
    }
    metrics_payload = {
        "model_version": MODEL_VERSION,
        "train_shape": list(x_train.shape),
        "test_shape": list(x_test.shape),
        "rf_recall": rf_metrics["recall"],
        "rf_precision": rf_metrics["precision"],
        "rf_f1": rf_metrics["f1"],
        "rf_roc_auc": rf_metrics["roc_auc"],
        "rf_threshold": rf_metrics["threshold"],
        "rf_fpr_at_threshold": rf_metrics["fpr_at_threshold"],
        "rf_confusion_matrix": rf_metrics["confusion_matrix"],
        "rf_roc_curve": rf_metrics["roc_curve"],
        "lr_recall": lr_metrics["recall"],
        "lr_precision": lr_metrics["precision"],
        "lr_f1": lr_metrics["f1"],
        "lr_roc_auc": lr_metrics["roc_auc"],
        "lr_threshold": lr_metrics["threshold"],
        "lr_fpr_at_threshold": lr_metrics["fpr_at_threshold"],
        "lr_confusion_matrix": lr_metrics["confusion_matrix"],
        "lr_roc_curve": lr_metrics["roc_curve"],
    }
    _save_json(models_dir / "threshold.json", threshold_payload)
    _save_json(models_dir / "eval_metrics.json", metrics_payload)

    print(f"RF metrics: Recall={rf_recall:.3f}, ROC-AUC={rf_roc_auc:.3f}")
    print(f"Artifacts saved in {models_dir}")
    return metrics_payload


if __name__ == "__main__":
    train_and_save()
